'use strict';
const $=id=>document.getElementById(id), enc=new TextEncoder();
let db, state, project, active, swReady=false, saveTimer, runTimer, toastTimer, revision=0, logs=0, compat=true, history=[], future=[], assetURL;
let storageAvailable=true, writeQueue=Promise.resolve(), previewURLs=[];
const errorText=e=>e?.message||e?.name||'El navegador canceló el acceso al almacenamiento.';
const uid=()=>crypto.randomUUID(), escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const textType=p=>/\.(html?|css|js|mjs|json|txt|md|svg|xml|csv|ts|jsx|tsx|map)$/i.test(p);
const mime=p=>({'html':'text/html','htm':'text/html','css':'text/css','js':'text/javascript','mjs':'text/javascript','json':'application/json','svg':'image/svg+xml','png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp','gif':'image/gif','mp3':'audio/mpeg','mp4':'video/mp4','woff2':'font/woff2','txt':'text/plain'})[p.split('.').pop().toLowerCase()]||'application/octet-stream';
function cleanPath(p){p=p.replace(/\\/g,'/').replace(/^\/+/, '');if(!p||p.split('/').some(x=>!x||x==='.'||x==='..')||p.includes('\0'))throw Error('Usa una ruta válida, por ejemplo css/estilo.css.');return p}
function notify(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function transaction(store,mode,action){return new Promise((resolve,reject)=>{let tx,r;try{tx=db.transaction(store,mode);r=action(tx.objectStore(store))}catch(e){reject(e||new Error('No se pudo abrir la transacción.'));return}const failure=()=>reject(tx.error||r?.error||new Error('El navegador canceló la transacción de almacenamiento.'));tx.oncomplete=()=>resolve(r?.result);tx.onerror=failure;tx.onabort=failure})}
async function serializeWorkspace(source){return {...source,formatVersion:2,projects:await Promise.all(source.projects.map(async p=>({...p,files:await Promise.all(p.files.map(async f=>({path:f.path,type:f.blob.type,bytes:new Uint8Array(await f.blob.arrayBuffer())})))})))}}
function hydrateWorkspace(saved){return {...saved,projects:saved.projects.map(p=>({...p,files:p.files.map(f=>({path:f.path,blob:f.blob||new Blob([f.bytes],{type:f.type||mime(f.path)})}))}))}}
async function persist(){clearTimeout(saveTimer);if(!db){storageAvailable=false;$('saveState').textContent='Solo esta sesión';return false}const snapshot=await serializeWorkspace(state);$('saveState').textContent='Guardando…';const operation=writeQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{let tx;try{tx=db.transaction(['workspace','projects'],'readwrite');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('No se pudo guardar.'));tx.onabort=()=>reject(tx.error||new Error('El navegador canceló el guardado.'));tx.objectStore('workspace').put(snapshot,'main');for(const p of snapshot.projects)tx.objectStore('projects').put(p)}catch(e){reject(e||new Error('No se pudo guardar.'))}}));writeQueue=operation;try{await operation;storageAvailable=true;$('saveState').textContent='Guardado en este dispositivo';return true}catch(e){const wasAvailable=storageAvailable;storageAvailable=false;$('saveState').textContent='Solo esta sesión';$('runtime').textContent='Sin guardado persistente · Exporta un respaldo';if(wasAvailable)notify('Puedes seguir probando. El guardado falló: '+errorText(e)+' Exporta un respaldo antes de salir.');return false}}
function queueSave(){clearTimeout(saveTimer);$('saveState').textContent='Cambios pendientes';saveTimer=setTimeout(()=>persist().catch(()=>{}),450)}
function file(path,content){return {path,blob:new Blob([content],{type:mime(path)})}}
const demo=`<!doctype html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mi primer proyecto</title>
  <link rel="stylesheet" href="css/estilo.css">
</head>
<body>
  <main>
    <span class="badge">HECHO POR TI</span>
    <h1>Las ideas empiezan<br>con un <em>hola.</em></h1>
    <p>Este es tu espacio para crear. Edita el código y mira cómo cobra vida.</p>
    <button id="hola">Probar JavaScript ↗</button>
    <p id="mensaje" aria-live="polite"></p>
  </main>
  <script src="js/app.js"></script>
</body>
</html>`;
function demoProject(){return {id:uid(),name:'Mi primer proyecto',folder:'Mis proyectos',entry:'index.html',files:[file('index.html',demo),file('css/estilo.css',`*{box-sizing:border-box}body{margin:0;background:#f3f5ef;color:#18231b;font-family:system-ui,sans-serif;min-height:100vh;display:grid;place-items:center}main{padding:35px;max-width:650px}.badge{font-size:11px;letter-spacing:3px;font-weight:700;color:#597442}h1{font-size:clamp(32px,7vw,62px);line-height:1.1;letter-spacing:-2px}em{color:#648941;font-style:normal}p{color:#6a7568;line-height:1.7}button{border:0;border-radius:30px;padding:16px 25px;background:#203b26;color:white;font-size:16px;cursor:pointer}`),file('js/app.js',`let clicks=0;document.getElementById('hola').onclick=()=>{clicks++;document.getElementById('mensaje').textContent='¡Funciona! Has pulsado '+clicks+' veces.';console.log('Clic',clicks);};console.info('Proyecto listo para crear.');`)]}}
function renderProjects(){const q=$('projectSearch').value.toLowerCase();$('projects').replaceChildren();for(const folder of state.folders){const box=document.createElement('div'),head=document.createElement('div');head.className='folderLabel';const label=document.createElement('span');label.textContent='▱ '+folder;head.append(label);const edit=document.createElement('button');edit.textContent='•••';edit.setAttribute('aria-label','Gestionar carpeta '+folder);edit.onclick=()=>folderOptions(folder);head.append(edit);box.append(head);for(const p of state.projects.filter(p=>p.folder===folder&&p.name.toLowerCase().includes(q))){const b=document.createElement('button');b.className='projectItem'+(p.id===state.current?' active':'');b.append(document.createTextNode('◇ '+p.name));const sub=document.createElement('small');sub.textContent=p.files.length+' archivos';b.append(sub);b.onclick=()=>selectProject(p.id);box.append(b)}$('projects').append(box)}}
async function selectProject(id,preferredPath){await flushEdit();state.current=id;project=state.projects.find(p=>p.id===id);active=project.files.find(f=>f.path===(preferredPath||project.activePath||project.entry))||project.files.find(f=>f.path===project.entry)||project.files[0];syncActiveEntry();render();await loadFile();queueSave();closeSidebar();await run()}
function syncActiveEntry(){project.activePath=active?.path;if(active&&/\.html?$/i.test(active.path)){project.entry=active.path;$('entry').value=active.path}}
async function openFile(path){await flushEdit();active=project.files.find(f=>f.path===path);syncActiveEntry();render();await loadFile();queueSave();if($('auto').checked)await run()}
function render(){renderProjects();$('projectName').textContent=project.name;$('projectFolder').textContent=project.folder.toUpperCase();$('files').replaceChildren();$('entry').replaceChildren();for(const f of project.files){$('files').add(new Option(f.path,f.path));if(/\.html?$/i.test(f.path))$('entry').add(new Option(f.path,f.path))}$('files').value=active?.path||'';if(!project.files.some(f=>f.path===project.entry))project.entry=project.files.find(f=>/\.html?$/i.test(f.path))?.path;$('entry').value=project.entry||'';$('fileCount').textContent=project.files.length+' archivos · '+(project.files.reduce((a,f)=>a+f.blob.size,0)/1024).toFixed(1)+' KB'}
async function loadFile(){if(assetURL)URL.revokeObjectURL(assetURL);history=[];future=[];const editable=active&&textType(active.path);$('editor').hidden=!editable;$('lines').hidden=!editable;$('binary').hidden=!!editable;$('editor').disabled=!editable;if(editable){$('editor').value=await active.blob.text();history=[$('editor').value]}else{$('assetPreview').replaceChildren();if(active&&active.blob.type.startsWith('image/')){assetURL=URL.createObjectURL(active.blob);const img=new Image();img.src=assetURL;
let storageAvailable=true, writeQueue=Promise.resolve(), previewURLs=[];
const errorText=e=>e?.message||e?.name||'El navegador canceló el acceso al almacenamiento.';img.alt=active.path;$('assetPreview').append(img)}}$('language').textContent=active?.path.split('.').pop().toUpperCase()||'SIN ARCHIVOS';updateLines()}
async function flushEdit(){if(active&&textType(active.path)&&!$('editor').disabled)active.blob=new Blob([$('editor').value],{type:mime(active.path)})}
function updateLines(){const e=$('editor');$('lines').textContent=Array.from({length:e.value.split('\n').length},(_,i)=>i+1).join('\n');const prefix=e.value.slice(0,e.selectionStart);$('cursor').textContent='Línea '+prefix.split('\n').length+' · Col '+(prefix.length-prefix.lastIndexOf('\n'));$('lines').scrollTop=e.scrollTop}
function edited(record=true){syncActiveEntry();if(record){if(history.at(-1)!==$ ('editor').value){history.push($('editor').value);if(history.length>100)history.shift()}future=[]}flushEdit();updateLines();queueSave();if($('auto').checked){clearTimeout(runTimer);runTimer=setTimeout(()=>run(),950)}}
function localPath(value,base){try{const url=new URL(value,'https://studio.invalid/'+base);if(url.origin!=='https://studio.invalid')return null;return decodeURIComponent(url.pathname.slice(1))}catch{return null}}
async function sessionPreview(p){for(const url of previewURLs)URL.revokeObjectURL(url);previewURLs=[];const urlFor=f=>{const url=URL.createObjectURL(f.blob);previewURLs.push(url);return url};const resolve=(value,base)=>p.files.find(f=>f.path===localPath(value,base));const entry=p.files.find(f=>f.path===p.entry);const doc=new DOMParser().parseFromString(await entry.blob.text(),'text/html');
const rewriteCSS=(text,base)=>text.replace(/url\(\s*(['"]?)([^)'"\s]+)\1\s*\)/gi,(all,quote,path)=>{const f=resolve(path,base);return f?'url("'+urlFor(f)+'")':all});
for(const link of [...doc.querySelectorAll('link[rel="stylesheet"][href]')]){const f=resolve(link.getAttribute('href'),p.entry);if(f){const style=doc.createElement('style');style.textContent=rewriteCSS(await f.blob.text(),f.path);link.replaceWith(style)}}
for(const script of doc.querySelectorAll('script[src]')){const f=resolve(script.getAttribute('src'),p.entry);if(f)script.setAttribute('src',urlFor(f))}
for(const el of doc.querySelectorAll('[src]')){if(el.tagName==='SCRIPT')continue;const f=resolve(el.getAttribute('src'),p.entry);if(f)el.setAttribute('src',urlFor(f))}
for(const style of doc.querySelectorAll('style'))style.textContent=rewriteCSS(style.textContent,p.entry);
return '<!doctype html>'+doc.documentElement.outerHTML}
async function run(){clearTimeout(runTimer);try{await flushEdit();syncActiveEntry();const p=project,request=++revision;const saved=await persist();if(request!==revision)return;if(!p.entry){notify('Añade un archivo HTML para ejecutarlo.');return}logs=0;$('console').replaceChildren();$('logCount').textContent='0';const frame=$('preview');frame.setAttribute('sandbox','allow-scripts allow-forms allow-modals allow-popups allow-downloads'+(compat?' allow-same-origin':''));if(swReady&&saved){frame.removeAttribute('srcdoc');frame.src=new URL('__preview__/'+p.id+'/'+p.entry.split('/').map(encodeURIComponent).join('/')+'?studioRun='+request,location.href).href;$('runtime').textContent=compat?'Modo de compatibilidad · Solo código de confianza':'Ejecución aislada · Proyectos locales'}else{const html=await sessionPreview(p);if(request!==revision)return;frame.removeAttribute('src');frame.srcdoc=html;$('runtime').textContent=saved?'Vista simple · Recarga para activar el ejecutor completo':'Solo esta sesión · Exporta antes de salir'} }catch(e){notify('No se pudo ejecutar: '+errorText(e))}}
function modal(title,body,ok='Guardar'){const d=$('dialog');$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialogOK').textContent=ok;d.returnValue='';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true}))}
async function newProject(paste=false){if(!await modal(paste?'Pegar código HTML':'Nuevo proyecto',`<label>Nombre<input id="nameInput" required value="Nuevo proyecto"></label><label>Carpeta<select id="folderChoice">${state.folders.map(f=>'<option>'+escapeHTML(f)+'</option>').join('')}</select></label>${paste?'<label>Código HTML<textarea id="pasteCode" required placeholder="Pega aquí tu código completo…"></textarea></label>':''}`,'Crear proyecto'))return;const p={id:uid(),name:$('nameInput').value.trim()||'Nuevo proyecto',folder:$('folderChoice').value,entry:'index.html',files:[file('index.html',paste?$('pasteCode').value:'<!doctype html>\n<html lang="es">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <title>Mi proyecto</title>\n</head>\n<body>\n  <h1>¡Hola, mundo!</h1>\n</body>\n</html>')]};state.projects.push(p);await selectProject(p.id)}
async function folderOptions(folder){if(!await modal('Carpeta',`<label>Nombre<input id="folderName" required value="${escapeHTML(folder)}"></label><p>Al cambiar el nombre se mueven sus proyectos. Solo puedes eliminar una carpeta vacía.</p><button type="button" id="deleteFolder" class="choice">Eliminar carpeta vacía</button>`))return;const name=$('folderName').value.trim();if(!name||state.folders.includes(name)&&name!==folder)return notify('Ese nombre ya existe.');state.folders[state.folders.indexOf(folder)]=name;state.projects.filter(p=>p.folder===folder).forEach(p=>p.folder=name);render();queueSave()}
$('dialogBody').addEventListener('click',async e=>{if(e.target.id==='deleteFolder'){const name=$('folderName').defaultValue;if(state.projects.some(p=>p.folder===name))return notify('Mueve los proyectos antes de eliminar la carpeta.');state.folders=state.folders.filter(f=>f!==name);$('dialog').close('cancel');renderProjects();queueSave()}});
async function projectOptions(){await modal('Gestionar proyecto',`<button type="button" class="choice" data-action="renameProject">Renombrar o mover de carpeta</button><button type="button" class="choice" data-action="duplicateProject">Duplicar proyecto</button><button type="button" class="choice" data-action="deleteProject">Eliminar proyecto</button>`,'Cerrar')}
$('dialogBody').addEventListener('click',async e=>{const a=e.target.dataset.action;if(!a)return;$('dialog').close('cancel');await new Promise(r=>setTimeout(r,0));if(a==='renameProject'){if(await modal('Editar proyecto',`<label>Nombre<input id="rename" required value="${escapeHTML(project.name)}"></label><label>Carpeta<select id="move">${state.folders.map(f=>`<option ${f===project.folder?'selected':''}>${escapeHTML(f)}</option>`).join('')}</select></label>`)){project.name=$('rename').value.trim()||project.name;project.folder=$('move').value;render();queueSave()}}if(a==='duplicateProject'){await flushEdit();const p=structuredClone(project);p.id=uid();p.name+=' · copia';state.projects.push(p);await selectProject(p.id)}if(a==='deleteProject'&&await modal('Eliminar proyecto',`<p>Se eliminará <b>${escapeHTML(project.name)}</b> de este dispositivo. Exporta una copia si quieres conservarlo.</p>`,'Eliminar')){const id=project.id;state.projects=state.projects.filter(p=>p.id!==id);if(db)await transaction('projects','readwrite',s=>s.delete(id)).catch(e=>notify(errorText(e)));active=null;if(!state.projects.length)state.projects.push(demoProject());await selectProject(state.projects[0].id)}});
async function newFile(){if(!await modal('Nuevo archivo o carpeta','<label>Ruta del archivo<input id="pathInput" required placeholder="css/estilo.css"></label><p>Las carpetas se crean al escribir una ruta. Ejemplo: js/app.js.</p>','Crear archivo'))return;try{const path=cleanPath($('pathInput').value.trim());if(project.files.some(f=>f.path===path))return notify('Ya existe ese archivo.');await flushEdit();active=file(path,'');project.files.push(active);syncActiveEntry();render();await loadFile();queueSave();if($('auto').checked)await run()}catch(e){notify(errorText(e))}}
async function fileOptions(){if(!active)return;if(!await modal('Archivo: '+active.path,`<label>Ruta o nombre<input id="renameFile" required value="${escapeHTML(active.path)}"></label><button type="button" class="choice" id="deleteFile">Eliminar archivo</button>`))return;try{const path=cleanPath($('renameFile').value.trim());if(project.files.some(f=>f!==active&&f.path===path))return notify('Ese archivo ya existe.');if(project.entry===active.path)project.entry=path;active.path=path;syncActiveEntry();render();queueSave();if($('auto').checked)await run();notify('Ruta actualizada. Revisa las referencias en tu código.')}catch(e){notify(errorText(e))}}
$('dialogBody').addEventListener('click',async e=>{if(e.target.id!=='deleteFile')return;$('dialog').close('cancel');await new Promise(r=>setTimeout(r,0));if(await modal('Eliminar archivo',`<p>¿Eliminar ${escapeHTML(active.path)}? Esta acción no se puede deshacer.</p>`,'Eliminar')){project.files=project.files.filter(f=>f!==active);active=null;await selectProject(project.id)}});
async function importFiles(list,isFolder=false){if(!list.length)return;await flushEdit();let target=project,root='';if(isFolder){root=list[0].webkitRelativePath.split('/')[0];target={id:uid(),name:root,folder:project.folder,entry:'index.html',files:[]}}let overwritten=0;for(const f of list){const path=cleanPath(isFolder?f.webkitRelativePath.split('/').slice(1).join('/'):f.name);if(target.files.some(x=>x.path===path))overwritten++}if(overwritten&&!await modal('Reemplazar archivos',`<p>${overwritten} archivos tienen el mismo nombre. ¿Reemplazarlos con los archivos importados?</p>`,'Reemplazar'))return;for(const f of list){const path=cleanPath(isFolder?f.webkitRelativePath.split('/').slice(1).join('/'):f.name), item={path,blob:f.slice(0,f.size,f.type||mime(path))};const i=target.files.findIndex(x=>x.path===path);if(i>=0)target.files[i]=item;else target.files.push(item)}const importedPaths=list.map(f=>cleanPath(isFolder?f.webkitRelativePath.split('/').slice(1).join('/'):f.name));const htmlPaths=importedPaths.filter(path=>/\.html?$/i.test(path));const preferredPath=(isFolder?htmlPaths.find(path=>/^index\.html?$/i.test(path)):null)||htmlPaths[0]||target.activePath||target.entry;active=null;if(isFolder)state.projects.push(target);await selectProject(target.id,preferredPath);notify(list.length+' archivos importados')}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function zipProject(){await flushEdit();const parts=[],central=[];let offset=0;for(const f of project.files){const name=enc.encode(f.path),bytes=new Uint8Array(await f.blob.arrayBuffer()),crc=crc32(bytes);const local=new Uint8Array(30+name.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);local.set(name,30);parts.push(local,bytes);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=local.length+bytes.length}const size=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);download(new Blob([...parts,...central,end],{type:'application/zip'}),project.name.replace(/[^\p{L}\p{N}_-]/gu,'-')+'.zip')}
function crc32(bytes){let crc=-1;for(const b of bytes){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return (crc^-1)>>>0}
async function backup(){await flushEdit();const projects=[];for(const p of state.projects){const files=[];for(const f of p.files){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f.blob)});files.push({path:f.path,data})}projects.push({...p,files})}download(new Blob([JSON.stringify({format:'fran-html-studio',version:1,folders:state.folders,projects})],{type:'application/json'}),'Fran-HTML-Studio-respaldo.json');notify('Respaldo exportado')}
async function restore(f){try{const b=JSON.parse(await f.text());if(b.format!=='fran-html-studio'||b.version!==1||!Array.isArray(b.projects)||!Array.isArray(b.folders))throw Error('Formato no compatible');const incoming=[];for(const p of b.projects){if(typeof p.name!=='string'||typeof p.folder!=='string'||!Array.isArray(p.files))throw Error('Proyecto inválido');const files=[];for(const f of p.files){const path=cleanPath(f.path);if(typeof f.data!=='string'||!/^data:[^,]*;base64,/.test(f.data))throw Error('Archivo inválido');const comma=f.data.indexOf(','),type=f.data.slice(5,comma).replace(';base64',''),raw=atob(f.data.slice(comma+1));files.push({path,blob:new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type})})}incoming.push({id:uid(),name:p.name,folder:p.folder,entry:p.entry,files})}if(!await modal('Restaurar respaldo',`<p>Se añadirán ${incoming.length} proyectos. Tus proyectos actuales se conservarán.</p>`,'Importar'))return;for(const p of incoming){if(!state.folders.includes(p.folder))state.folders.push(p.folder);state.projects.push(p)}await persist();renderProjects();notify('Respaldo restaurado')}catch(e){notify('No se pudo restaurar: '+errorText(e))}}
function closeSidebar(){document.body.classList.remove('menuOpen');$('overlay').hidden=true}
$('menu').onclick=()=>{document.body.classList.add('menuOpen');$('overlay').hidden=false};$('closeMenu').onclick=$('overlay').onclick=closeSidebar;
$('newProject').onclick=()=>newProject();$('paste').onclick=()=>newProject(true);$('newFolder').onclick=async()=>{if(await modal('Nueva carpeta','<label>Nombre<input id="folderNew" required placeholder="Experimentos"></label>','Crear')){const name=$('folderNew').value.trim();if(!name||state.folders.includes(name))return notify('Nombre vacío o ya existente.');state.folders.push(name);renderProjects();queueSave()}};
$('projectSearch').oninput=renderProjects;$('projectOptions').onclick=projectOptions;$('newFile').onclick=newFile;$('fileOptions').onclick=fileOptions;
$('files').onchange=()=>openFile($('files').value);$('entry').onchange=async()=>{await openFile($('entry').value);if(!$('auto').checked)await run()};$('editor').oninput=()=>edited();$('editor').onscroll=updateLines;$('editor').onclick=$('editor').onkeyup=updateLines;
$('editor').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const el=$('editor');el.setRangeText('  ',el.selectionStart,el.selectionEnd,'end');edited()}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();run()}};
$('undo').onclick=()=>{if(history.length<2)return;future.push(history.pop());$('editor').value=history.at(-1);edited(false)};$('redo').onclick=()=>{if(!future.length)return;const next=future.pop();history.push(next);$('editor').value=next;edited(false)};
$('find').onclick=()=>{$('findBar').hidden=!$('findBar').hidden;if(!$('findBar').hidden)$('query').focus()};$('nextMatch').onclick=()=>{const q=$('query').value;if(!q)return;const el=$('editor'),start=el.value.indexOf(q,el.selectionEnd),i=start>=0?start:el.value.indexOf(q);if(i<0)return notify('No hay coincidencias.');el.focus();el.setSelectionRange(i,i+q.length);const line=el.value.slice(0,i).split('\n').length;el.scrollTop=Math.max(0,(line-4)*parseFloat(getComputedStyle(el).lineHeight));updateLines()};$('replaceAll').onclick=()=>{const q=$('query').value;if(!q)return;const el=$('editor'),count=el.value.split(q).length-1;el.value=el.value.split(q).join($('replacement').value);edited();notify(count+' coincidencias reemplazadas')};
$('run').onclick=$('reload').onclick=run;$('auto').onchange=()=>{if($('auto').checked)run();else clearTimeout(runTimer)};$('export').onclick=()=>zipProject().catch(e=>notify(errorText(e)));$('downloadFile').onclick=async()=>{await flushEdit();if(active)download(active.blob,active.path.split('/').pop())};$('backup').onclick=()=>backup().catch(e=>notify(errorText(e)));$('restore').onclick=()=>$('backupInput').click();$('backupInput').onchange=async e=>{if(e.target.files[0])await restore(e.target.files[0]);e.target.value=''};
$('importFiles').onclick=()=>$('fileInput').click();$('importFolder').onclick=()=>$('folderInput').click();for(const [id,folder]of [['fileInput',false],['folderInput',true]])$(id).onchange=async e=>{try{await importFiles([...e.target.files],folder)}catch(err){notify(errorText(err))}e.target.value=''};
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length)importFiles([...e.dataTransfer.files]).catch(err=>notify(errorText(err)))});
let focusReturnView='split', focusTrigger=null;
function updateFocusViewport(){if(document.body.classList.contains('focus-mode'))document.documentElement.style.setProperty('--focus-height',(window.visualViewport?.height||window.innerHeight)+'px')}
function setWorkspaceView(view){$('workspace').dataset.view=view;document.querySelectorAll('.segmented button').forEach(b=>{const selected=b.dataset.view===view;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))})}
function enterFocus(view,trigger){if(!document.body.classList.contains('focus-mode'))focusReturnView=$('workspace').dataset.view;focusTrigger=trigger||document.activeElement;closeSidebar();setWorkspaceView(view);document.body.classList.add('focus-mode');$('workspace').dataset.focus=view;$('focusExit').hidden=false;updateFocusViewport();if(view==='preview')run();$('focusExit').focus()}
function exitFocus(){if(!document.body.classList.contains('focus-mode'))return;document.body.classList.remove('focus-mode');delete $('workspace').dataset.focus;$('focusExit').hidden=true;document.documentElement.style.removeProperty('--focus-height');setWorkspaceView(focusReturnView);focusTrigger?.focus();updateLines()}
$('focusExit').onclick=exitFocus;
window.visualViewport?.addEventListener('resize',updateFocusViewport);window.addEventListener('resize',updateFocusViewport);
document.querySelectorAll('.segmented button').forEach(b=>{b.onclick=()=>{if(b.dataset.view==='split'){exitFocus();setWorkspaceView('split');if($('auto').checked)run()}else enterFocus(b.dataset.view,b)}});
$('device').onchange=()=>{$('preview').style.width=$('device').value==='fluid'?'100%':$('device').value+'px'};$('fullscreen').onclick=()=>enterFocus('preview',$('fullscreen'));window.addEventListener('keydown',e=>{if(e.key==='Escape')exitFocus()});
$('toggleConsole').onclick=()=>$('console').hidden=!$('console').hidden;$('clearConsole').onclick=()=>{$('console').replaceChildren();logs=0;$('logCount').textContent=0};window.addEventListener('message',e=>{if(e.source!==$('preview').contentWindow||e.data?.kind!=='fran-console')return;const row=document.createElement('div');row.className='log '+(['error','warn','log','info'].includes(e.data.level)?e.data.level:'log');row.textContent=String(e.data.text).slice(0,20000);$('console').append(row);if($('console').children.length>200)$('console').firstChild.remove();$('logCount').textContent=++logs;if(e.data.level==='error')$('console').hidden=false;$('console').scrollTop=$('console').scrollHeight});
let fontSize=14;for(const [id,delta]of [['fontDown',-1],['fontUp',1]])$(id).onclick=()=>{fontSize=Math.min(24,Math.max(11,fontSize+delta));document.documentElement.style.setProperty('--font',fontSize+'px')};
$('divider').onpointerdown=e=>{const d=$('divider');d.setPointerCapture(e.pointerId);d.onpointermove=ev=>{const r=$('workspace').getBoundingClientRect(),mobile=matchMedia('(max-width:800px)').matches;const pct=mobile?(ev.clientY-r.top)/r.height*100:(ev.clientX-r.left)/r.width*100;document.documentElement.style.setProperty('--ratio',Math.max(20,Math.min(80,pct))+'%')};d.onpointerup=()=>d.onpointermove=null};$('divider').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();let value=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--ratio'));value+=['ArrowLeft','ArrowUp'].includes(e.key)?-5:5;document.documentElement.style.setProperty('--ratio',Math.max(20,Math.min(80,value))+'%')};
$('settings').onclick=async()=>{if(await modal('Ejecución',`<label><input id="compatInput" type="checkbox" ${compat?'checked':''}> Modo de compatibilidad</label><p>Actívalo para proyectos de confianza que necesiten localStorage, IndexedDB, cookies o permisos. El código podrá acceder al origen de esta app y a sus datos locales.</p><p>El modo aislado reduce ese acceso. Algunas APIs, peticiones externas o librerías pueden exigir HTTPS, permisos o configuración CORS.</p><p>Los recursos con rutas relativas funcionan al importar todos los archivos del proyecto. PHP, Python, Node.js y bases de datos requieren un servidor externo. Las rutas que empiezan por / apuntan a la raíz del dominio.</p>`,'Aplicar')){compat=$('compatInput').checked;$('runtime').textContent=compat?'Modo de compatibilidad · Solo código de confianza':'Ejecución aislada · Proyectos locales';run()}};
$('help').onclick=()=>modal('Tu taller de HTML',`<p><b>1.</b> Crea un proyecto, pega HTML o importa archivos. «Importar carpeta» conserva las rutas del proyecto; si el teléfono no ofrece esa opción, crea las rutas e importa los archivos por separado.</p><p><b>2.</b> Abre o importa un HTML y se mostrará automáticamente en Resultado. Con «Vista en vivo», tus cambios se aplican al dejar de escribir. También puedes elegir otro HTML desde el selector del resultado.</p><p><b>3.</b> Cambia entre Código, Dividida y Resultado. Arrastra el separador para ajustar los paneles.</p><p><b>4.</b> Guarda un respaldo antes de borrar datos del navegador. Los proyectos se guardan solo en este navegador y dispositivo, no se sincronizan con GitHub.</p><p>Exportar crea un ZIP con todos los recursos. «Archivo» descarga el archivo abierto. La app no impone un límite de líneas; la memoria y el almacenamiento del navegador sí tienen límites.</p><p>Los permisos de cámara, micrófono, ubicación y descargas dependen del navegador. Un bucle infinito puede bloquear la pestaña; no hay aislamiento de CPU.</p>`,'Entendido');
async function init(){try{try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('fran-html-studio',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('workspace'))r.result.createObjectStore('workspace');if(!r.result.objectStoreNames.contains('projects'))r.result.createObjectStore('projects',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Almacenamiento no disponible.'))});const saved=await transaction('workspace','readonly',s=>s.get('main'));if(saved)state=hydrateWorkspace(saved)}catch(e){storageAvailable=false;db?.close();db=null;notify('El almacenamiento no está disponible. Puedes probar y exportar tus proyectos durante esta sesión.')}if(!state?.projects?.length){const p=demoProject();state={folders:['Mis proyectos','Experimentos'],projects:[p],current:p.id}}project=state.projects.find(p=>p.id===state.current)||state.projects[0];state.current=project.id;active=project.files.find(f=>f.path===project.activePath)||project.files.find(f=>f.path===project.entry)||project.files[0];syncActiveEntry();render();await loadFile();if('serviceWorker'in navigator&&location.protocol!=='file:'){try{await navigator.serviceWorker.register('sw.js?v=20261004-5',{updateViaCache:'none'});await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller||!navigator.serviceWorker.controller.scriptURL.includes('v=20261004-5'))await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Activación pendiente')),6000);navigator.serviceWorker.addEventListener('controllerchange',()=>{clearTimeout(timeout);resolve()},{once:true})});swReady=true}catch(e){$('runtime').textContent='Vista simple · Recarga o publica mediante HTTPS'}}await run()}catch(e){$('runtime').textContent='No se pudo iniciar';notify('No se pudo iniciar: '+errorText(e))}}
init();
